### PR TITLE
Update Hapi and Joi

### PR DESCRIPTION
**Pull request by andrewMacmurray**
update dependencies

### CODE REVIEW

**Comment by iteles** [comment]
-

**Comment by iteles** [comment]
Sorry, GitHub for mobile lends itself to pressing the wrong thing often! Didn't mean to close this. 

@andrewMacmurray Did you run through the app locally to make sure everything is still as expected? I'll do the same on my side this afternoon. 
Both hapi and joi follow semver so just double checking the breaking changes don't affect the app.

**Comment by andrewMacmurray** [comment]
@iteles yep it works locally and the tests pass locally / on circle

**Comment by iteles** [comment]
Confirmed! 👍

**Pull request merged**
